version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: tokubetsu
      POSTGRES_PASSWORD: tokubetsu
      POSTGRES_DB: tokubetsu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_USER=tokubetsu
      - DB_PASSWORD=tokubetsu
      - DB_NAME=tokubetsu
      - DB_PORT=5432
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: go run cmd/server/main.go

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    command: npm run dev

volumes:
  postgres_data: 