services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: tokubetsu
      POSTGRES_PASSWORD: tokubetsu
      POSTGRES_DB: tokubetsu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_USER=tokubetsu
      - DB_PASSWORD=tokubetsu
      - DB_NAME=tokubetsu
      - DB_PORT=5432
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ./main

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8080
      - HOST=0.0.0.0
    depends_on:
      - backend
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 